title: Fabien Schurter
timezone: Europe/Paris
keep_files:
  - assets
  - vendor
collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
  -
    scope:
      path: _pages/fr
    values:
      lang: fr-FR
      description: Portfolio professionnel de Fabien Schurter, développeur web.
      main_title: Fabien Schurter
      main_subtitle: Développeur web
