# Jekyll config
keep_files:
  - assets
  - vendor
  - .gitkeep
timezone: Europe/Paris
kramdown:
  auto_ids: false
  input: kramdown
collections:
  pages:
    output: true
    permalink: /:path:output_ext
defaults:
  - scope:
      path: ''
    values:
      layout: default

# Custom config
asset_url: /assets
sections:
  - intro
  - skills
  - work
  - availability
  - contact
polyfills:
  - default
  - fetch
  - getComputedStyle
  - NodeList.prototype.@@iterator
