timezone: Europe/Paris
exclude:
  - _pages/LICENSE
keep_files:
  - assets
  - vendor
  - .gitkeep
kramdown:
  auto_ids: false
  input: kramdown
sections:
  - intro
  - work
  - contact
asset_url: /assets
copyright_year: 2016
collections:
  pages:
    output: true
    permalink: /:path:output_ext
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
