timezone: Europe/Paris
keep_files:
  - assets
  - vendor
kramdown:
  auto_ids: false
collections:
  pages:
    output: true
    permalink: /:path
sections:
  - intro
  - skills
  - work
  - experience
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
