# Jekyll config
collections:
  pages:
    output: true
    permalink: /:path:output_ext
keep_files:
  - assets
  - vendor
  - .gitkeep
timezone: Europe/Paris
defaults:
  - scope:
      path: ''
    values:
      layout: default
kramdown:
  auto_ids: false
  input: kramdown

# Custom config
asset_url: /assets
sections:
  - intro
  - work
  - contact
