timezone: Europe/Paris
keep_files:
  - assets
  - vendor
collections:
  pages:
    output: true
    permalink: /:path
sections:
  - header
  - intro
  - skills
  - work
  - footer
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
