version: '2'

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    environment:
      CANONICAL_ROOT: http://docker.vm
    volumes:
      - /opt/codebase
      - ./app/jekyll:/opt/codebase/app/jekyll

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - '80:80'
    depends_on:
      - app

  builder:
    image: website_app
    environment:
      ENVIRONMENT: dev
      DISABLE_WATCH: 0
    command: ./node_modules/.bin/gulp
    volumes_from:
      - app
    volumes:
      - ./app/view/theme:/opt/codebase/app/view/theme
      - ./gulpfile.js:/opt/codebase/gulpfile.js
    ports:
      - '35729:35729'
    depends_on:
      - app
