version: '2'

services:
  builder:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    volumes:
      - '/Users/fabien/Sites/cv/gulpfile.js:/opt/project/gulpfile.js'
      - '/Users/fabien/Sites/cv/app:/opt/project/app'
      - '/Users/fabien/Sites/cv/web/vendor:/opt/project/web/vendor'
      - '/opt/project/web'
      - '/etc/nginx'
    ports:
      - '35729:35729'
    command: "sh -c 'ENVIRONMENT=dev ./node_modules/.bin/gulp'"

  app:
    image: fabschurt/nginx
    depends_on:
      - builder
    volumes_from:
      - builder
    ports:
      - '80:80'
