version: '2'

services:
  app:
    image: website_app
    build:
      context: .
      args:
        ENVIRONMENT: dev
        CANONICAL_ROOT: http://docker.vm
    volumes:
      - /opt/project/web
    ports:
      - '80:80'

  builder:
    image: website_app
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./gulpfile.js:/opt/project/gulpfile.js
      - ./app:/opt/project/app
      - ./web/vendor:/opt/project/web/vendor
    ports:
      - '35729:35729'
    environment:
      ENVIRONMENT: dev
      DISABLE_WATCH: 0
      CANONICAL_ROOT: http://docker.vm
    command: "sh -c './node_modules/.bin/gulp'"
