version: '2'

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: dev
        CANONICAL_ROOT: http://docker.vm
    volumes:
      - /opt/codebase
    ports:
      - '80:80'

  builder:
    image: website_app
    environment:
      ENVIRONMENT: dev
      DISABLE_WATCH: 0
      CANONICAL_ROOT: http://docker.vm
    command: "sh -c './node_modules/.bin/gulp'"
    volumes_from:
      - app
    volumes:
      - ./app:/opt/codebase/app
      - ./web/vendor:/opt/codebase/web/vendor
      - ./gulpfile.js:/opt/codebase/gulpfile.js
    ports:
      - '35729:35729'
    depends_on:
      - app
