version: '2'

services:
  builder:
    build:
      context: .
      args:
        ENVIRONMENT: dev
        NO_WATCH: 1
    volumes:
      - '/Users/fabien/Sites/cv/app:/opt/project/app'
      - '/opt/project/web'
      - '/etc/nginx'
    ports:
      - '35729:35729'
    command: "sh -c 'ENVIRONMENT=dev ./node_modules/.bin/gulp watch'"

  web:
    image: fabschurt/nginx
    depends_on:
      - builder
    volumes_from:
      - builder
    ports:
      - '80:80'
